### ISSUE TITLE
How to build with Windows?

### ISSUE THREAD

**Issue by lazydino** [LarsFlaeten/ork#1]
Hi,

What is the platform tested for succesful build? I am running Windows 10 Pro, and trying to build the project with Visual Studio 2013. I was not able to fix various CMake issues to have it generate Visual Studio solution file. CMake runs fine and generate makefiles on Linux, but I don't have a good video adapter to test it on linux machine. What do you recommend?  Cmake could not find GLFW package with Visual C++ 2013. Can MinGW do it? What is the easiest way to try ORK and Proland? I might have access to a Ubuntu 16 machine that equpped with a better GPU. Would that be an ideal platform to try it?

**Comment by LarsFlaeten** [comment]
Hi, I cannot help with building this on Windows, as I have myself only tested on Linux (ubuntu 16.04 LTS), on a Thinkpad T420 wit a NVS 4200M graphics adapter

**Comment by KnIfER** [comment]
using cmake gui and msvc,
just comment out `PKG_CHECK_MODULES()`  
and write   
`
include_directories("E:/XuNi/proland-4.0/glew-2.1.0/include")
link_directories("E:/XuNi/proland-4.0/glew-2.1.0/lib/Release/Win32")
`  
and so on...
